# Generated by Django 5.1.7 on 2025-03-29 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='infection',
            name='user',
            field=models.ForeignKey(help_text='The user who is infected', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='infections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='locationhistory',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_histories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='relevantlocation',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relevant_locations', to=settings.AUTH_USER_MODEL),
        ),
    ]
