# Generated by Django 5.1.7 on 2025-03-30 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_infection_user_locationhistory_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('symptoms_appeared_date', models.DateTimeField()),
                ('diagnosis_date', models.DateTimeField(blank=True, null=True)),
                ('symptoms', models.TextField()),
                ('illness', models.CharField(choices=[('mono', 'Mono'), ('hfm', 'Hand-Foot-Mouth Disease'), ('other', 'Other')], max_length=100)),
                ('was_diagnosed', models.BooleanField(default=False)),
            ],
        ),
    ]
