# Generated by Django 5.1.7 on 2025-03-30 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_physicalreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='learn_link',
            field=models.CharField(default='nothing', max_length=100),
            preserve_default=False,
        ),
    ]
