# Generated by Django 5.1.7 on 2025-03-30 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_physicalreport_disease'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicalreport',
            name='disease',
            field=models.CharField(choices=[('Mononucleosis (Mono)', 'Mononucleosis (Mono)'), ('HIV & AIDS', 'HIV & AIDS')], max_length=100),
        ),
    ]
