# Generated by Django 5.1.7 on 2025-03-30 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_alter_physicalreport_disease'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicalReport2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(choices=[('Mononucleosis (Mono)', 'Mononucleosis (Mono)')], max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='PhysicalReport',
        ),
    ]
