# Generated by Django 5.1.7 on 2025-03-30 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_notificationv2'),
        ('App', '0007_physicalreport2_delete_physicalreport'),
    ]

    operations = [
    ]
