# Generated by Django 5.1.7 on 2025-03-30 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_merge_20250330_0450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicalreport2',
            name='disease',
            field=models.CharField(choices=[('Mononucleosis (Mono)', 'Mononucleosis (Mono)'), ('HIV & AIDS', 'HIV & AIDS')], max_length=100),
        ),
    ]
