# Generated by Django 5.1.7 on 2025-03-30 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_alter_physicalreport2_disease'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirborneReport2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', models.CharField(max_length=255)),
                ('symptoms_appeared_date', models.DateTimeField()),
                ('diagnosis_date', models.DateTimeField(blank=True, null=True)),
                ('was_diagnosed', models.BooleanField(default=False)),
                ('disease', models.ForeignKey(help_text='The disease associated with this airborne report', on_delete=django.db.models.deletion.CASCADE, related_name='airborne_reports', to='App.disease')),
            ],
        ),
        migrations.DeleteModel(
            name='AirborneReport',
        ),
    ]
