# Generated by Django 5.1.7 on 2025-03-30 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_notificationv2_notif_strength_and_more'),
        ('App', '0012_alter_physicalreport2_disease'),
    ]

    operations = [
    ]
