# Generated by Django 5.1.7 on 2025-03-30 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_merge_20250330_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationv2',
            name='notif_strength',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', help_text='Type of disease (air or physical)', max_length=20),
        ),
        migrations.AlterField(
            model_name='physicalreport2',
            name='disease',
            field=models.CharField(choices=[('Mononucleosis (Mono)', 'Mononucleosis (Mono)'), ('HIV & AIDS', 'HIV & AIDS'), ('Osteoarthritis', 'Osteoarthritis'), ('Rheumatoid Arthritis', 'Rheumatoid Arthritis'), ('Type 2 Diabetes', 'Type 2 Diabetes'), ('Hypertension', 'Hypertension'), ('Coronary Heart Disease', 'Coronary Heart Disease'), ('Chronic Obstructive Pulmonary Disease (COPD)', 'Chronic Obstructive Pulmonary Disease (COPD)'), ('Stroke', 'Stroke'), ('Chronic Kidney Disease', 'Chronic Kidney Disease'), ("Alzheimer's Disease", "Alzheimer's Disease"), ('Osteoporosis', 'Osteoporosis'), ('Breast Cancer', 'Breast Cancer'), ('Lung Cancer', 'Lung Cancer'), ('Appendicitis', 'Appendicitis'), ('Gallstones', 'Gallstones'), ('Migraine', 'Migraine'), ('Back Pain', 'Back Pain')], max_length=100),
        ),
    ]
